export const ADD_CUSTOMER = 'ADD_CUSTOMERS'
export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'
export const FILTER_CUSTOMERS = 'FILTER_CUSTOMERS'
export const CLEAR_FILTER = 'CLEAR_FILTER'
export const SET_CUSTOMER = 'SET_CUSTOMER'
export const CLEAR_CURRENT = 'CLEAR_CURRENT'
export const SET_LOADING = 'SET_LOADING'
export const SET_LOADINGFORM = 'SET_LOADINGFORM'

  
